
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessCenterApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Exercise
{

    public int Id { get; set; }

    public int ClientId { get; set; }

    public int TrainerId { get; set; }

    public string ExerciseType { get; set; }

    public int RepeatOnceEvery { get; set; }

    public int NumberOfSets { get; set; }

    public int RepeatsPerSet { get; set; }

    public System.DateTime BeginAt { get; set; }



    public virtual Client Client { get; set; }

    public virtual Trainer Trainer { get; set; }

}

}
