

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessCenterApp.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FitnessCenterBaseEntities : DbContext
{
    public FitnessCenterBaseEntities()
        : base("name=FitnessCenterBaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Exercise> Exercise { get; set; }

    public virtual DbSet<Gender> Gender { get; set; }

    public virtual DbSet<Photo> Photo { get; set; }

    public virtual DbSet<Requests> Requests { get; set; }

    public virtual DbSet<RequestStatus> RequestStatus { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<Specialization> Specialization { get; set; }

    public virtual DbSet<Trainer> Trainer { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

