
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessCenterApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TrainerRequests
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrainerRequests()
    {

        this.Trainer = new HashSet<Trainer>();

        this.TrainerRequests1 = new HashSet<TrainerRequests>();

    }


    public int Id { get; set; }

    public int RequestId { get; set; }

    public Nullable<int> NextId { get; set; }



    public virtual Requests Requests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Trainer> Trainer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainerRequests> TrainerRequests1 { get; set; }

    public virtual TrainerRequests TrainerRequests2 { get; set; }

}

}
