//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerSchedule
    {
        public int Id { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
