//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerSchedule
    {
        public int Id { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
